### ISSUE TITLE
Minimal Image for QEMU (v7 & v8)

### ISSUE THREAD

**Issue by jleni** [Zondax/zondbox-images#22]
Adjust layers and recipes to make images as small as possible.

Remove sound support, bluetooth, wifi, etc. and other unnecessary dependencies.

Restructure build process and use Yocto/bitbake approach.

**Comment by igoropaniuk** [comment]
Done, to test:
```
$ git clone git@github.com:Zondax/zondbox-images.git -b dev
$ make pull_manifest
$ make build qemu && make build qemu8
$ make run qemu # qemu8
```
